# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wared - Ahlam Abdullah - Final' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wared - Ahlam Abdullah - Final
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end
